const nl: Record<string, string> = {
  "Recipe name is required.": "Receptnaam is verplicht.",
  "Failed to save recipe. Please try again.": "Recept opslaan mislukt. Probeer het opnieuw.",
  "Basic Info": "Basisgegevens",
  "Name": "Naam",
  "e.g. Grilled Chicken with Salsa": "bijv. Gegrilde Kip met Salsa",
  "Description": "Beschrijving",
  "A brief description of the dish...": "Een korte beschrijving van het gerecht...",
  "Details": "Details",
  "Cooking time (min)": "Bereidingstijd (min)",
  "Kitchen": "Keuken",
  "Status": "Status",
  "Rating": "Waardering",
  "Ingredients": "Ingrediënten",
  "Add": "Toevoegen",
  "No ingredients yet.": "Nog geen ingrediënten.",
  "Add ingredient": "Ingrediënt toevoegen",
  "Qty": "Aantal",
  "Unit": "Eenheid",
  "Saving...": "Opslaan...",
  "Save Changes": "Wijzigingen Opslaan",
  "Create Recipe": "Recept Aanmaken",
  "to try": "proberen",
  "success": "geslaagd",
  "needs tweak": "aanpassen nodig",
  "failure": "mislukt",
  "archived": "gearchiveerd",
  "Quantity must be greater than 0.": "Hoeveelheid moet groter zijn dan 0.",
  "Ingredient name is required.": "Ingrediëntnaam is verplicht.",
  "Cooking time cannot be negative.": "Bereidingstijd kan niet negatief zijn.",

  "pcs": "stk",
  "tsp": "tl",
  "tbsp": "el",
  "pinch": "snufje",
  "User not found": "Gebruiker niet gevonden",
  "Wrong password": "Ongeldig wachtwoord",
  "Login failed. Please try again.": "Inloggen mislukt. Probeer het opnieuw.",
  "Username": "Gebruikersnaam",
  "Password": "Wachtwoord",
  "Logging in...": "Inloggen...",
  "Login": "Inloggen",
  "Logout": "Uitloggen",
  "Taste tracker": "Taste Tracker",
  "Taste Tracker": "Taste Tracker",
  "Recipes & Wines": "Recipes & Wines",
  "Recipes and wines": "Recipes & wines",
  "Sprints & Log": "Sprints & Log",
  "System / Beheer": "System / Beheer",
  "New Recipe": "Nieuw Recept",
  "All": "Alle",
  "No recipes yet.": "Nog geen recepten.",
  "Create your first recipe": "Maak je eerste recept aan",
  "No recipes with status \"{status}\".": "Geen recepten met status \"{status}\".",
  "Delete this recipe?": "Dit recept verwijderen?",
  "This action cannot be undone.": "Dit kan niet ongedaan worden gemaakt.",
  "Edit": "Bewerk",
  "Delete": "Verwijder",
  "Ingredient": "Ingrediënt",
  "Quantity": "Hoeveelheid",
  "No ingredients listed.": "Geen ingrediënten vermeld.",
  "Back to recipe": "Terug naar recept",
  "Edit Recipe": "Recept Bewerken",
  "Search a kitchen…": "Zoek een keuken…",
  "Clear": "Wissen",
  "Welcome to": "Welkom bij",
  "Built for personal use and development": "Gemaakt voor persoonlijk gebruik en ontwikkeling",
  "Time": "Tijd",
  "Steps": "Bereidingswijze",
  "Add step": "Stap toevoegen",
  "No steps yet.": "Nog geen stappen.",
  "Step": "Stap",
  "Search": "Zoeken",
  "Search recipes\u2026": "Zoek recepten\u2026",
  "Search results for \"{q}\"": "Zoekresultaten voor \"{q}\"",
  "No recipes found for \"{q}\".": "Geen recepten gevonden met \"{q}\".",
  "Clear search": "Wis zoekopdracht",
  "Search workouts…": "Zoek trainingen…",
  "Template": "Sjabloon",
  "No sessions found for \"{q}\".": "Geen trainingen gevonden voor \"{q}\".",
  "Recipe": "Recept",
  "Recipes": "Recepten",
  "g": "gr",
  "kg": "kg",
  "ml": "ml",
  "l": "l",

  "Workout Studio": "Workout Studio",
  "Resistance": "Krachttraining",
  "Bodyweight": "Lichaamsgewicht",
  "Cardio": "Cardio",
  "Isometric": "Isometrisch",
  "Category": "Categorie",
  "Distance (km)": "Afstand (km)",
  "Time (MM:SS)": "Tijd (MM:SS)",
  "Avg HR (bpm)": "Hartslag (bpm)",
  "RPE (0-10)": "RPE (0-10)",
  "Added weight (kg)": "Extra gewicht (kg)",
  "Added/Assisted (kg)": "Extra/Assisted (kg)",
  "Per side": "Per zijde",
  "per side": "per zijde",
  "Per Side": "Per zijde",
  "Workouts": "Workouts",
  "Templates": "Sjablonen",
  "New Template": "Nieuw Sjabloon",
  "Import": "Importeren",
  "Import Template": "Sjabloon importeren",
  "Import Workout Sjabloon": "Workout-sjabloon importeren",
  "Paste JSON or upload a file": "Plak JSON-code of upload een .json bestand",
  "Select JSON file": "Selecteer JSON-bestand",
  "Invalid JSON format": "Ongeldig JSON-formaat",
  "Template name is required in JSON": "Sjabloonnaam is verplicht in JSON",
  "At least one exercise is required in JSON": "Ten minste één oefening is verplicht in JSON",
  "Importing...": "Importeren...",
  "Template name is required.": "Sjabloonnaam is verplicht.",
  "Exercise Name": "Naam oefening",
  "Exercise name is required.": "Oefeningsnaam is verplicht.",
  "Edit Template": "Sjabloon Bewerken",
  "Create Template": "Sjabloon Aanmaken",
  "Sets": "Sets",
  "Reps": "Reps",
  "Weight": "Gewicht",
  "kg (optional)": "kg (optioneel)",
  "Optional": "Optioneel",
  "optional": "optioneel",
  "Exercises": "Oefeningen",
  "No exercises yet. Click \"Add\" to get started.": "Nog geen oefeningen. Klik op \"Toevoegen\" om te beginnen.",
  "Add exercise": "Oefening toevoegen",
  'Add "{name}"': 'Voeg "{name}" toe',
  "Start workout": "Sessie starten",
  "Quick start": "Snel starten",
  "No templates yet.": "Nog geen sjablonen.",
  "Create your first template": "Maak je eerste sjabloon aan",
  "Active": "Actief",
  "Completed": "Voltooid",
  "No active sessions.": "Geen actieve trainingen.",
  "No completed sessions yet.": "Nog geen voltooide trainingen.",
  "Session": "Training",
  "Duration": "Duur",
  "Notes": "Notities",
  "Add note": "Notitie toevoegen",
  "No notes for this workout.": "Geen notities voor deze training.",
  "Complete workout": "Training afronden",
  "Finish": "Afronden",
  "Add set": "Set toevoegen",
  "Set": "Set",
  "Mark set as completed": "Markeer set als voltooid",
  "Complete": "Voltooid",
  "exercise": "oefening",
  "Next": "Volgende",
  "Previous": "Vorige",
  "Exercise": "Oefening",
  "Progress": "Voortgang",
  "History": "Geschiedenis",
  "Personal records": "Persoonlijke records",
  "Best set": "Beste set",
  "Total volume": "Totaal volume",
  "Sessions": "Sessies",
  "No data yet for this exercise.": "Nog geen gegevens voor deze oefening.",
  "Delete this workout?": "Deze training verwijderen?",
  "Delete this template?": "Dit sjabloon verwijderen?",
  "Export": "Exporteer",
  "Export JSON": "Exporteer JSON",
  "Copied!": "Gekopieerd!",
  "Back to templates": "Terug naar sjablonen",
  "Back to overview": "Terug naar overzicht",
  "Workout Studio Template": "Workout Studio Sjabloon",
  "Choose a template or start fresh": "Kies een sjabloon of begin leeg",
  "or": "of",
  "Start blank workout": "Begin lege training",
  "Started at": "Gestart op",
  "Completed at": "Voltooid op",
  "in progress": "bezig",
  "Toggle history": "Toon geschiedenis",
  "Remove": "Verwijderen",
  "A brief description...": "Een korte beschrijving...",
  "Sets must be at least 1.": "Sets moet minimaal 1 zijn.",
  "Reps must be at least 1.": "Herhalingen moeten minimaal 1 zijn.",
  "Failed to save template. Please try again.": "Sjabloon opslaan mislukt. Probeer het opnieuw.",
  "e.g. Full Body": "bijv. Full Body",
  "No exercises yet.": "Nog geen oefeningen.",
  "No exercises yet. Add one to start.": "Nog geen oefeningen. Voeg er een toe om te beginnen.",
  "Target muscle groups": "Doelspiergroepen",
  "Estimated time (minutes)": "Geschatte tijd (minuten)",
  "Estimated time": "Geschatte tijd",
  "min": "min",
  "Target": "Doel",
  "Done": "Klaar",
  "Finished": "Voltooid",
  "Workout title": "Trainingsnaam",
  "Edit Exercise": "Oefening bewerken",
  "Replace Exercise": "Oefening vervangen",
  "View History": "Geschiedenis bekijken",
  "Workout Review & Edits": "Training Beoordelen & Aanpassen",
  "Duration Editor": "Tijdsduur aanpassen",
  "Performance Summary": "Prestatiesamenvatting",
  "Total volume lifted": "Totaal volume getild",
  "PRs (Personal Records)": "Persoonlijke Records (PR's)",
  "New Record!": "Nieuw Record!",
  "Max weight": "Zwaarste set",
  "Max reps": "Meeste herhalingen",
  "Max sets": "Meeste sets",
  "Max volume": "Hoogste volume",
  "Max distance": "Grootste afstand",
  "Max duration": "Langste duur",
  "Total workout volume": "Totaal volume workout",
  "Workout duration": "Langste workout duur",
  "Exercises completed": "Meeste oefeningen",
  "was": "was",
  "Save": "Opslaan",
  "Discard Workout": "Training weggooien",
  "Are you sure you want to discard this workout session?": "Weet je zeker dat je deze training wilt weggooien?",
  "You have unfinished sets. Mark them as skipped or return to workout?": "Je hebt onafgeronde sets. Wil je deze markeren als overgeslagen of teruggaan naar de training?",
  "Return to workout": "Terug naar training",
  "Finish anyway": "Toch afronden",
  "History for {name}": "Geschiedenis van {name}",
  "Select Exercise to Replace": "Kies oefening ter vervanging",
  "Add Exercise": "Oefening toevoegen",
  "Hours": "Uur",
  "Minutes": "Min",
  "Seconds": "Sec",
  "Reorder": "Volgorde aanpassen",
  "Reorder Exercises": "Oefeningen herordenen",
  "Move Up": "Omhoog",
  "Move Down": "Omlaag",
  "Apply": "Toepassen",
  "Cancel": "Annuleren",
  "Last workout: today": "Laatste training: vandaag",
  "Last workout: yesterday": "Laatste training: gisteren",
  "Last workout: {days} days ago": "Laatste training: {days} dagen geleden",
  "Last workout: no workouts completed yet": "Laatste training: nog geen trainingen voltooid",
  "Total amount of exercises done": "Totaal aantal oefeningen gedaan",
  "Total volume moved": "Totaal volume verplaatst",
  "trainingen voltooid": "trainingen voltooid",
  "was je laatste training": "was je laatste training",
  "geleden was je laatste training": "geleden was je laatste training",
  "oefeningen gedaan": "oefeningen gedaan",
  "workouts gedaan": "workouts gedaan",
  "volume verplaatst": "volume verplaatst",
  "Leave Workout": "Training verlaten",
  "You are currently in an active workout. Are you sure you want to leave?": "Je bent momenteel bezig met een training. Weet je zeker dat je wilt weggaan?",
  "Leave": "Verlaten",
  "barbell": "Barbell",
  "dumbbell": "Dumbbell",
  "kettlebell": "Kettlebell",
  "cable": "Kabel",
  "machine": "Machine",
  "band": "Weerstandsband",
  "ball": "Bal",
  "none": "Geen",
  "Barbell": "Barbell",
  "Dumbbell": "Dumbbell",
  "Kettlebell": "Kettlebell",
  "Hex Bar": "Hex Bar",
  "Weight Plate": "Halterschijf",
  "Cable": "Kabel",
  "Machine": "Machine",
  "Smith Machine": "Smith Machine",
  "Suspension Trainer": "Suspension Trainer",
  "Weighted Vest": "Gewichtsvest",
  "Assisted Machine": "Assisted Machine",
  "Resistance Band": "Weerstandsband",
  "Medicine Ball": "Medicine Bal",
  "Swiss Ball": "Swiss Ball",
  "Ball": "Bal",
  "Sandbag": "Zandzak",
  "Sled": "Slee",
  "Plyo Box": "Plyo Box",
  "Cardio Machine": "Cardio Apparaat",
  "Rest time (sec)": "Rusttijd (sec)",
  "Next milestone": "Volgende mijlpaal",
  "naar volgende mijlpaal": "tot volgende mijlpaal",
  "tot volgende mijlpaal": "tot volgende mijlpaal",
  "Rest": "Rusten",
  "Skip": "Overslaan",
  "Search exercises…": "Zoek oefeningen…",
  "Equipment": "Materiaal",
  "Rest Time": "Rusttijd",
  "Account": "Account",
  "Logged in as": "Ingelogd als",
  "Go to Workouts home": "Naar startpagina trainingen",
  "Go to Recipes home": "Naar startpagina recepten",
  "Resting": "Rusten",
  "seconds": "seconden",
  "sec": "sec",
  "Volume": "Volume",
  "Total reps": "Totaal herhalingen",
  "Total duration": "Totale tijdsduur",
  "Oefening": "Oefening",
  "Merge": "Samenvoegen",
  "Merge exercises": "Oefeningen samenvoegen",
  "Merge Exercise": "Oefening samenvoegen",
  "Source exercise": "Bron-oefening",
  "Target exercise": "Doel-oefening",
  "Select target exercise": "Selecteer doel-oefening",
  "Source and target exercise names must be different.": "Bron- en doel-oefening moeten verschillend zijn.",
  "Exercises merged successfully.": "Oefeningen succesvol samengevoegd.",
  "Failed to merge exercises.": "Samenvoegen van oefeningen mislukt.",
  "Merging...": "Samenvoegen...",
  "All templates and workout history for the source exercise will be migrated to the target exercise.": "Alle sjablonen en trainingsgeschiedenis van de bron-oefening worden overgezet naar de doel-oefening.",
  "All exercises completed!": "Alle oefeningen voltooid!",
  "Good job! Finish your workout to save your results.": "Goed gedaan! Rond je training af om de resultaten op te slaan.",
  "Lyric Quotes": "Lyric Quotes",
  "You": "You",
  "Bekijk quotes": "Bekijk quotes",
  "Poems for each other": "Poems",
  "Weight & Measurements": "Gewicht & Metingen",
  "Body": "Body",
  "body": "body",
  "Body measurements & progress tracking": "Lichaamsmetingen & voortgang",
  "Height (cm)": "Lengte (cm)",
  "Weight (kg)": "Gewicht (kg)",
  "Body fat (%)": "Vetpercentage (%)",
  "Skeletal muscle (kg)": "Skeletspier (kg)",
  "Fat mass (kg)": "Vetmassa (kg)",
  "Photos": "Foto's",
  "Log Entry": "Meting registreren",
  "+ meting": "+ meting",
  "Meting": "Meting",
  "meting": "meting",
  "Save Log": "Meting opslaan",
  "Delete Log": "Meting verwijderen",
  "Date": "Datum",
  "Latest log": "Laatste meting",
  "No measurements logged yet.": "Nog geen metingen geregistreerd.",
  "Track your physical progress": "Volg je fysieke voortgang",
  "Upload photo": "Foto uploaden",
  "Optimizing photo...": "Foto optimaliseren...",
  "Uploading photo...": "Foto uploaden...",
  "Failed to upload photo": "Foto uploaden mislukt",
  "Delete photo": "Foto verwijderen",
  "Are you sure you want to delete this log?": "Weet je zeker dat je deze meting wilt verwijderen?",
  "Height is automatically filled from previous log.": "Lengte is automatisch ingevuld op basis van de vorige meting.",
  "Body Fat": "Vet",
  "Skeletal Muscle": "Skeletspier",
  "Fat Mass": "Vetmassa",
  "Height": "Lengte",
  "Lichaamsmetingen": "Lichaamsmetingen",
  "Body Measurements": "Lichaamsmetingen",
  "+ Lichaamsmetingen toevoegen": "+ Lichaamsmetingen toevoegen",
  "Lichaamsmetingen verbergen": "Lichaamsmetingen verbergen",
  "Middel": "Middel",
  "Waist": "Middel",
  "Borst": "Borst",
  "Chest": "Borst",
  "Heupen": "Heupen",
  "Hips": "Heupen",
  "Biceps": "Biceps",
  "Biceps / Armen": "Biceps",
  "Bovenbenen": "Bovenbenen",
  "Thighs": "Bovenbenen",
  "Schouders": "Schouders",
  "Shoulders": "Schouders",
  "Nek": "Nek",
  "Neck": "Nek",
  "Kuiten": "Kuiten",
  "Calves": "Kuiten",
  "Sets with 0 reps": "Sets met 0 herhalingen",
  "You have completed sets with 0 reps. Do you want to finish anyway?": "Je hebt voltooide sets met 0 herhalingen. Wil je toch afronden?",

  "Wines": "Wijnen",
  "Wine": "Wijn",
  "New Wine": "Nieuwe Wijn",
  "Add Wine": "Wijn Toevoegen",
  "Edit Wine": "Wijn Bewerken",
  "Brand / Winery": "Merk / Wijnhuis",
  "Wine type": "Wijntype",
  "Variety / Grape": "Druif / Stijl",
  "Variety": "Druif / Stijl",
  "Vintage / Year": "Oogstjaar",
  "Country / Region": "Land / Streek",
  "Where bought": "Gekocht bij",
  "Purchase location": "Gekocht bij",
  "Select location": "Selecteer locatie",
  "Supermarket": "Supermarkt",
  "Wine shop": "Wijnwinkel",
  "Winery": "Wijnhuis",
  "Webshop / Online": "Webshop / Online",
  "Hospitality / Restaurant": "Horeca / Restaurant",
  "Gift": "Cadeau gekregen",
  "Other": "Overig",
  "supermarket": "Supermarkt",
  "wine_shop": "Wijnwinkel",
  "winery": "Wijnhuis",
  "online": "Webshop / Online",
  "restaurant": "Horeca / Restaurant",
  "gift": "Cadeau gekregen",
  "other": "Overig",
  "Notes / Why you liked it": "Notities / Waarom je deze lekker vond",
  "Label photo": "Foto van etiket",
  "Red": "Rood",
  "White": "Wit",
  "Rosé": "Rosé",
  "Sparkling": "Mousserend",
  "Dessert": "Dessertwijn",
  "red": "Rood",
  "white": "Wit",
  "rose": "Rosé",
  "sparkling": "Mousserend",
  "dessert": "Dessertwijn",
  "No wines yet.": "Nog geen wijnen.",
  "Add your first wine": "Voeg je eerste wijn toe",
  "Delete this wine?": "Deze wijn verwijderen?",
  "Save Wine": "Wijn Opslaan",
  "Saving wine...": "Wijn opslaan...",
  "Brand is required.": "Merk / Wijnhuis is verplicht.",
  "Variety is required.": "Druif / Stijl is verplicht.",
  "Background Settings": "Achtergrond instellingen",
  "Blur": "Vervaging",
  "Brightness": "Helderheid",
  "Background Image": "Achtergrond afbeelding",
  "Custom URL": "Aangepaste URL",
  "Upload Image": "Foto uploaden",
  "Reset to Default": "Herstel standaard",
  "Dark": "Donker",
  "Enter image URL...": "Voer afbeelding URL in...",

  "Cashflow": "Cashflow",
  "Facturatie": "Facturatie",
  "Dashboard": "Dashboard",
  "Projecten": "Projecten",
  "Facturen": "Facturen",
  "Klanten": "Klanten",
  "Handelsnamen": "Handelsnamen",
  "Nieuw project": "Nieuw project",
  "Nieuwe factuur": "Nieuwe factuur",
  "Nieuwe klant": "Nieuwe klant",
  "Nieuwe handelsnaam": "Nieuwe handelsnaam",
  "Project aanmaken": "Project aanmaken",
  "Klant aanmaken": "Klant aanmaken",
  "Handelsnaam aanmaken": "Handelsnaam aanmaken",
  "Factuur aanmaken": "Factuur aanmaken",
  "Omzet afgelopen 12 maanden": "Omzet afgelopen 12 maanden",
  "Openstaand": "Openstaand",
  "Concept": "Concept",
  "Betaald": "Betaald",
  "Verzonden": "Verzonden",
  "Te laat": "Te laat",
  "Verwacht": "Verwacht",
  "Totaal": "Totaal",
  "Verwachte inkomsten": "Verwachte inkomsten",
  "draft": "Concept",
  "sent": "Verzonden",
  "paid": "Betaald",
  "overdue": "Te laat",
  "one-time": "Eenmalig",
  "monthly": "Maandelijks",
  "Eenmalig": "Eenmalig",
  "Maandelijks": "Maandelijks",
  "Projecttype": "Projecttype",
  "Klant": "Klant",
  "Handelsnaam": "Handelsnaam",
  "Locatie": "Locatie",
  "Projectnaam": "Projectnaam",
  "Projectomschrijving": "Projectomschrijving",
  "Klantnaam": "Klantnaam",
  "Klantemail": "Klantemail",
  "Klantadres": "Klantadres",
  "Standaardtarief (€/uur)": "Standaardtarief (€/uur)",
  "Factuurnummer": "Factuurnummer",
  "Datum van facturering": "Datum van facturering",
  "Datum van dienstverlening": "Datum van dienstverlening",
  "Datum van verzending": "Datum van verzending",
  "Vervaldatum": "Vervaldatum",
  "KOR (Kleineondernemersregeling)": "KOR (Kleineondernemersregeling)",
  "KOR van toepassing": "KOR van toepassing",
  "Factuurregels": "Factuurregels",
  "Omschrijving": "Omschrijving",
  "Aantal": "Aantal",
  "Eenheidsprijs (€)": "Eenheidsprijs (€)",
  "Totaal (€)": "Totaal (€)",
  "Reiskosten": "Reiskosten",
  "Regel toevoegen": "Regel toevoegen",
  "Verwijder regel": "Verwijder regel",
  "Factuurtotaal": "Factuurtotaal",
  "Opslaan als concept": "Opslaan als concept",
  "Opslaan en verzenden": "Opslaan en verzenden",
  "Markeer als betaald": "Markeer als betaald",
  "PDF downloaden": "PDF downloaden",
  "PDF genereren...": "PDF genereren...",
  "Factuurdetails": "Factuurdetails",
  "Projectgegevens": "Projectgegevens",
  "Klantgegevens": "Klantgegevens",
  "Betalingsinformatie": "Betalingsinformatie",
  "Betalingsreferentie": "Betalingsreferentie",
  "IBAN": "IBAN",
  "KVK-nummer": "KVK-nummer",
  "BTW-nummer": "BTW-nummer",
  "Adres": "Adres",
  "Totaal te betalen": "Totaal te betalen",
  "Geen factuurregels.": "Geen factuurregels.",
  "Geen projecten gevonden.": "Geen projecten gevonden.",
  "Geen klanten gevonden.": "Geen klanten gevonden.",
  "Geen facturen gevonden.": "Geen facturen gevonden.",
  "Geen handelsnamen gevonden.": "Geen handelsnamen gevonden.",
  "Maak je eerste handelsnaam aan": "Maak je eerste handelsnaam aan",
  "Maak je eerste klant aan": "Maak je eerste klant aan",
  "Maak je eerste project aan": "Maak je eerste project aan",
  "Maak je eerste factuur aan": "Maak je eerste factuur aan",
  "Selecteer klant": "Selecteer klant",
  "Selecteer project": "Selecteer project",
  "Selecteer handelsnaam": "Selecteer handelsnaam",
  "Nieuwe klant aanmaken": "Nieuwe klant aanmaken",
  "Annuleer": "Annuleer",
  "Project bewerken": "Project bewerken",
  "Klant bewerken": "Klant bewerken",
  "Handelsnaam bewerken": "Handelsnaam bewerken",
  "Factuur bewerken": "Factuur bewerken",
  "Dit project verwijderen?": "Dit project verwijderen?",
  "Deze klant verwijderen?": "Deze klant verwijderen?",
  "Deze handelsnaam verwijderen?": "Deze handelsnaam verwijderen?",
  "Deze factuur verwijderen?": "Deze factuur verwijderen?",
  "Bezig met opslaan...": "Bezig met opslaan...",
  "Facturen ({count})": "Facturen ({count})",
  "Totaal gefactureerd": "Totaal gefactureerd",
  "Projectnaam is verplicht.": "Projectnaam is verplicht.",
  "Klantnaam is verplicht.": "Klantnaam is verplicht.",
  "Handelsnaam is verplicht.": "Handelsnaam is verplicht.",
  "Selecteer een klant.": "Selecteer een klant.",
  "Selecteer een project.": "Selecteer een project.",
  "Geen regels toegevoegd.": "Geen regels toegevoegd.",
  "Factuurnummer is verplicht.": "Factuurnummer is verplicht.",
  "Factuurnummer is al in gebruik": "Factuurnummer is al in gebruik",
  "Invoice number must be unique": "Factuurnummer is al in gebruik",
  "Prijs per eenheid (€)": "Prijs per eenheid (€)",
  "Prijs per eenheid": "Prijs per eenheid",
  "Uren": "Uren",
  "Dienst": "Dienst",
  "Korting": "Korting",
  "Percentage (%)": "Percentage (%)",
  "Bedrag (€)": "Bedrag (€)",
  "per uur": "per uur",
  "per km": "per km",
  "uur": "uur",
  "km": "km",

  "Rep Timer": "Rep Timer",
  "Start Timer": "Timer starten",
  "Pause": "Pauzeren",
  "Resume": "Hervatten",
  "Reset": "Resetten",
  "Finish & Save Set": "Voltooien & Set opslaan",
  "Complete Rep": "Rep voltooien",
  "Target Time": "Doeltijd",
  "Timed Rep": "Tijdsgebaseerde rep",
  "Reset to target time": "Streeftijd herstellen",
  "Save target time": "Doeltijd opslaan",
  "Save actual time": "Gemeten tijd opslaan",
  "Your account has been paused. Please contact an administrator.": "Uw account is gepauzeerd. Neem contact op met de beheerder.",
  "User Management & Monitoring": "Gebruikersbeheer & Monitoring",
  "Pause Account": "Account pauzeren",
  "Unpause Account": "Account hervatten",
  "Email Address": "E-mailadres",
  "Module Access": "Module toegang",
  "Last Login": "Laatst ingelogd",
  "Account Status": "Account status",
  "Paused": "Gepauzeerd",
  "Never": "Nooit",
  "Total Users": "Totaal gebruikers",
  "Active Users": "Actieve gebruikers",
  "Paused Accounts": "Gepauzeerde accounts",
  "Total Permissions": "Totaal permissies",
  "Search users...": "Zoek gebruikers...",
  "Filter exercises...": "Oefeningen zoeken...",
  "All categories": "Alle categorieën",
  "All equipment": "Alle materialen",
  "Clear filters": "Filters wissen",
  "No exercises found matching your filters.": "Geen oefeningen gevonden die voldoen aan je filters.",
  "Free Weights": "Vrije gewichten",
  "Machines": "Apparaten",
  "Functional": "Functioneel",

  "Lobby Control": "Lobby Control",
  "Game servers": "Game servers",
  "No servers yet.": "Nog geen servers.",
  "Je hebt momenteel geen toegang tot specifieke servers. Neem contact op met de beheerder.": "Je hebt momenteel geen toegang tot specifieke servers. Neem contact op met de beheerder.",
  "Minecraft Server Monitor-toegang": "Minecraft Server Monitor-toegang",
  "servers geselecteerd": "servers geselecteerd",
  "Geen Minecraft servers gevonden.": "Geen Minecraft servers gevonden.",
  "Server toegang bijgewerkt": "Server-toegang bijgewerkt",
  "Server toegang wijzigen mislukt": "Server-toegang wijzigen mislukt",
  "Create your first server": "Maak je eerste server aan",
  "New Server": "Nieuwe Server",
  "Server name": "Servernaam",
  "Server slug": "Server-ID",
  "Slug must be 3-32 chars, lowercase, hyphens only.": "ID moet 3-32 tekens zijn, kleine letters en koppeltekens.",
  "Game version": "Spelversie",
  "Engine": "Engine",
  "Vanilla": "Vanilla",
  "Fabric": "Fabric",
  "Offline mode": "Offline modus",
  "Fire tick": "Vuurtick",
  "Online": "Online",
  "Offline": "Offline",
  "Starting...": "Starten...",
  "Stopping...": "Stoppen...",
  "Start": "Starten",
  "Stop": "Stoppen",
  "Restart": "Herstarten",
  "Console": "Console",
  "Send command": "Stuur commando",
  "Type a command...": "Typ een commando...",
  "Players": "Spelers",
  "No players online.": "Geen spelers online.",
  "Total playtime": "Totale speeltijd",
  "Last seen": "Laatst gezien",
  "Op": "Op",
  "Deop": "Deop",
  "Kick": "Verwijder",
  "Ban": "Verban",
  "Properties": "Instellingen",
  "Save Properties": "Instellingen Opslaan",
  "Mods": "Mods",
  "Datapacks": "Datapakketten",
  "Resourcepacks": "Resourcepakketten",
  "Upload file": "Bestand uploaden",
  "Upload files": "Bestanden uploaden",
  "Uploading files...": "Bestanden uploaden...",
  "Uploaded": "Geüpload",
  "failed": "mislukt",
  "Duplicate files detected": "Dubbele bestanden gedetecteerd",
  "Duplicate file detected": "Dubbel bestand gedetecteerd",
  "The following file already exists on the server. What would you like to do?": "Het volgende bestand bestaat al op de server. Wat wil je doen?",
  "The following files already exist on the server. What would you like to do?": "De volgende bestanden bestaan al op de server. Wat wil je doen?",
  "Replace": "Vervangen",
  "Replace existing": "Bestaande vervangen",
  "Skip duplicate": "Dubbele overslaan",
  "Skip duplicates": "Dubbelen overslaan",
  "No new files to upload.": "Geen nieuwe bestanden om te uploaden.",
  "Copy from server": "Kopieer van server",
  "No files yet.": "Nog geen bestanden.",
  "Save as Template": "Opslaan als Sjabloon",
  "Template name": "Sjabloonnaam",
  "Speedrun": "Speedrun",
  "1-Click Speedrun": "1-Klik Speedrun",
  "Start fresh world": "Nieuwe wereld starten",
  "Inherit from server": "Overerven van server",
  "Creating server...": "Server aanmaken...",
  "Create Server": "Server Aanmaken",
  "Server Dashboard": "Server Dashboard",
  "Server not found": "Server niet gevonden",
  "The requested server does not exist or has been removed.": "De opgevraagde server bestaat niet of is verwijderd.",
  "Back to server overview": "Terug naar serveroverzicht",
  "File Manager": "Bestandsbeheer",
  "World Map": "Wereldkaart",
  "Open in new tab": "Openen in nieuw tabblad",
  "Fullscreen": "Volledig scherm",
  "Exit Fullscreen": "Volledig scherm sluiten",
  "The world map is not generated yet. Start the server with the Pl3xMap mod to generate the map.": "De wereldkaart is nog niet gegenereerd. Start de server met de Pl3xMap mod om de kaart aan te maken.",
  "The Pl3xMap world map is being initialized by the server. It will appear automatically once ready.": "De Pl3xMap wereldkaart wordt geïnitialiseerd door de server. De kaart verschijnt automatisch zodra deze gereed is.",
  "World map viewer for": "Wereldkaart weergave voor",
  "Crash report": "Crashrapport",
  "Server failed to start": "Server kon niet starten",
  "Inherits from template": "Overerft van sjabloon",
  "players online": "spelers online",
  "Delete Server": "Server Verwijderen",
  "Also delete files from disk": "Verwijder ook bestanden van schijf",
  "Danger Zone": "Gevarenzone",
  "Irreversible actions that affect this server.": "Onomkeerbare acties die invloed hebben op deze server.",
  "Permanently remove this server from the overview and optionally delete world and configuration files.": "Verwijder deze server definitief uit het overzicht en wis eventueel wereld- en configuratiebestanden.",
  "General": "Algemeen",
  "Gameplay": "Gameplay",
  "World & Generation": "Wereld & Generatie",
  "Performance": "Prestaties",
  "Advanced & Custom": "Geavanceerd & Aangepast",
  "Server Port": "Serverpoort",
  "Max Players": "Max. aantal spelers",
  "Message of the Day (MOTD)": "Serverbericht (MOTD)",
  "Whitelist": "Wachtlijst (Whitelist)",
  "Enforce Whitelist": "Whitelist forceren",
  "Hide Online Players": "Online spelers verbergen in lijst",
  "Gamemode": "Spelmodus",
  "Force Gamemode": "Spelmodus forceren",
  "Survival": "Overleving (Survival)",
  "Creative": "Creatief (Creative)",
  "Adventure": "Avontuur (Adventure)",
  "Spectator": "Toeschouwer (Spectator)",
  "Difficulty": "Moeilijkheidsgraad",
  "Peaceful": "Vredig (Peaceful)",
  "Easy": "Makkelijk (Easy)",
  "Normal": "Normaal (Normal)",
  "Hard": "Moeilijk (Hard)",
  "Hardcore Mode": "Hardcore modus",
  "PvP Combat": "PvP gevechten",
  "Allow Flight": "Vliegen toestaan",
  "Enable Command Blocks": "Command blocks inschakelen",
  "World Name": "Wereldnaam",
  "World Seed": "Wereld seed",
  "World Type": "Wereldtype",
  "Default": "Standaard",
  "Flat": "Vlak (Flat)",
  "Large Biomes": "Grote biomen (Large Biomes)",
  "Amplified": "Versterkt (Amplified)",
  "Single Biome": "Enkel bioom (Single Biome)",
  "Generate Structures": "Structuren genereren",
  "Allow Nether": "Nether dimensie inschakelen",
  "Spawn Monsters": "Monsters spawnen",
  "Spawn Animals": "Dieren spawnen",
  "Spawn NPCs (Villagers)": "NPCs / Dorpsbewoners spawnen",
  "Spawn Protection (blocks)": "Spawnbeveiliging (blokken)",
  "View Distance (chunks)": "Zichtafstand (chunks)",
  "Simulation Distance (chunks)": "Simulatieafstand (chunks)",
  "Player Idle Timeout (min)": "Speler time-out bij inactiviteit (min)",
  "Entity Broadcast Range (%)": "Entiteit zendbereik (%)",
  "Search properties...": "Zoek eigenschappen...",
  "Add Property": "Eigenschap Toevoegen",
  "Property Key": "Sleutelnaam",
  "Property Value": "Waarde",
  "Custom Properties": "Aangepaste eigenschappen",
  "No custom properties added.": "Geen aangepaste eigenschappen toegevoegd.",
  "No properties found matching your search.": "Geen eigenschappen gevonden die voldoen aan de zoekopdracht.",
  "Saved successfully!": "Succesvol opgeslagen!",
  "Allow cracked clients": "Niet-officiële / cracked accounts toestaan",
  "Kick idle players after X minutes (0 = disabled)": "Inactieve spelers kicken na X minuten (0 = uitgeschakeld)",
  "Radius in blocks where non-ops cannot place or break blocks": "Radius in blokken waar niet-ops niet kunnen bouwen of slopen",
  "One life only, players cannot respawn in survival": "Slechts één leven, spelers kunnen niet herspawnen",
  "Server is running": "Server is actief",
  "Server is running: only live-swappable properties (Game Mode, Difficulty, Whitelist, Idle Timeout) can be modified via console commands. Stop the server to edit other properties.": "Server is actief: alleen dynamische instellingen (Spelmodus, Moeilijkheidsgraad, Whitelist, Idle Timeout) kunnen worden aangepast via console-commando's. Stop de server om overige instellingen te wijzigen.",
  "Live command": "Live commando",
  "Requires server stop": "Serverstop vereist",
  "Live applied": "Live toegepast",
  "Import Server": "Server Importeren",
  "Import an existing Minecraft server folder from the host machine": "Importeer een bestaande Minecraft servermap vanaf de server",
  "Detected unlinked servers": "Gevonden ongekoppelde servers",
  "No unlinked servers found in servers directory": "Geen ongekoppelde servers gevonden in de servermap",
  "Inspect folder": "Inspecteer map",
  "Inspect": "Inspecteren",
  "Inspecting...": "Inspecteren...",
  "Folder path on server": "Maplocatie op de server",
  "e.g. /home/stevo/minecraft/servers/my-server": "bijv. /home/stevo/minecraft/servers/my-server",
  "Server imported successfully!": "Server succesvol geïmporteerd!",
  "Importing server...": "Server importeren...",
  "Valid server folder": "Geldige servermap",
  "Invalid server folder": "Ongeldige servermap",
  "Select detected server": "Selecteer gevonden server",
  "Custom path": "Aangepast pad",
  "Scan servers directory": "Scan servermap",
  "Properties found": "server.properties aanwezig",
  "World directory found": "Wereldmap aanwezig",
  "Jar file found": "Jar-bestand aanwezig",
  "EULA accepted": "EULA geaccepteerd",
  "Detected Engine": "Gedetecteerde engine",
  "Detected Version": "Gedetecteerde versie",
  "Engine & Version": "Engine & Versie",
  "Settings": "Instellingen",
  "Mods & Files": "Mods & Bestanden",
  "Upload Mods (.jar)": "Mods uploaden (.jar)",
  "Upload Datapacks (.zip)": "Datapacks uploaden (.zip)",
  "Upload Resourcepacks (.zip)": "Resourcepacks uploaden (.zip)",
  "No files added to this template yet.": "Nog geen bestanden toegevoegd aan dit sjabloon.",
  "Creating template...": "Sjabloon aanmaken...",
  "Template created successfully!": "Sjabloon succesvol aangemaakt!",
  "Add mod": "Mod toevoegen",
  "Create a reusable server template with preconfigured version, engine, mods and settings": "Maak een herbruikbaar serversjabloon met voorgeconfigureerde versie, engine, mods en instellingen",
  "Unban": "Deblokkeren",
  "Unban Player": "Speler deblokkeren",
  "Pardon": "Deblokkeren",
  "Banned": "Geblokkeerd",
  "Banned Players": "Geblokkeerde Spelers",
  "No banned players.": "Geen geblokkeerde spelers.",
  "Unban this player?": "Deze speler deblokkeren?",
  "Ban this player?": "Deze speler blokkeren?",
  "Copy server path": "Kopieer serverpad",
  "Copy path": "Pad kopiëren",
  "Server path": "Serverpad",

  "Pulse": "Pulse",
  "No users found.": "Geen gebruikers gevonden.",
  "Email bewerken": "E-mail bewerken",
  "E-mailadres bijgewerkt": "E-mailadres bijgewerkt",
  "Opslaan mislukt": "Opslaan mislukt",
  "Account gepauzeerd": "Account gepauzeerd",
  "Account geactiveerd": "Account geactiveerd",
  "Status wijzigen mislukt": "Status wijzigen mislukt",
  "Module toegang bijgewerkt": "Module toegang bijgewerkt",
  "Permissies wijzigen mislukt": "Permissies wijzigen mislukt",

  "Login as user": "Inloggen als",
  "Test as user": "Test als gebruiker",
  "Impersonate user": "Inloggen als deze gebruiker",
  "Switching user...": "Overschakelen...",
  "You are currently logged in as {username} (impersonated by {admin})": "Je bent momenteel ingelogd als {username} (geïmpersoneerd door {admin})",
  "Stop impersonation": "Impersonatie beëindigen",
  "Return to {admin}": "Terugkeren naar {admin}",
  "Returning to admin...": "Terugschakelen...",
  "Test mode active": "Testmodus actief",

  "RAM Allocation": "RAM-geheugentoewijzing",
  "Memory & Java": "Geheugen & Java",
  "Memory & Performance": "Geheugen & Prestaties",
  "Garbage Collector & Performance": "Garbage Collector & Prestaties",
  "GC Profile": "GC-profiel",
  "Aikar's Flags (G1GC)": "Aikar's Flags (G1GC)",
  "Generational ZGC": "Generational ZGC",
  "Generational ZGC (Java 21+)": "Generational ZGC (Java 21+)",
  "Standard JVM": "Standaard JVM",
  "Optimized for Minecraft tick consistency and low GC latency.": "Geoptimaliseerd voor Minecraft tick-consistentie en minimale GC-pauzes.",
  "Ultra-low latency garbage collection (<1ms) on Java 21+.": "Ultra-lage latentie (<1ms GC-pauzes) voor consistente tick-tijden op Java 21+.",
  "Standard JVM garbage collection without Minecraft-specific tuning.": "Standaard JVM garbage collection zonder specifieke Minecraft-optimalisaties.",
  "Select standard memory allocation or customize Java arguments for optimal server performance.": "Kies een standaard geheugentoewijzing of stel aangepaste Java-argumenten in voor optimale serverprestaties.",
  "Custom": "Aangepast",
  "Custom Java Args": "Aangepaste Java-args",
  "Custom Java Arguments": "Aangepaste Java-argumenten",
  "Additional Java Arguments": "Extra Java-argumenten",
  "Include -Xms and -Xmx memory flags and any custom JVM parameters.": "Voeg -Xms en -Xmx geheugenvlaggen en eventuele custom JVM-parameters toe.",
  "RAM flags are configured automatically. Add extra JVM or GC flags here.": "RAM-vlaggen worden automatisch geconfigureerd. Voeg hier eventuele extra JVM- of GC-vlaggen toe.",
  "RAM and GC optimizations are configured automatically. Add extra JVM flags here.": "RAM- en GC-optimalisaties worden automatisch geconfigureerd. Voeg hier eventuele extra JVM-vlaggen toe.",
  "Launch Command Preview": "Voorbeeld van startopdracht",
  "Minimaal": "Minimaal",
  "Standaard": "Standaard",
  "Aanbevolen": "Aanbevolen",
  "Zwaar": "Zwaar",

  "Minor": "Minor",
  "Minor Tracker": "Minor Tracker",
  "Minor App": "Minor App",
  "Minor Portfolio": "Minor Portfolio",
  "Future-proof met AI overview": "Future-proof met AI overview",
  "Sprintbeheer & Portfolio": "Sprintbeheer & Portfolio",
  "Sprints & LU's": "Sprints & LU's",
  "Sprints": "Sprints",
  "Nieuwe Sprint": "Nieuwe Sprint",
  "Sprint": "Sprint",
  "Sprint aanmaken": "Sprint aanmaken",
  "Sprint bewerken": "Sprint bewerken",
  "Sprint verwijderen": "Sprint verwijderen",
  "Sprintnummer": "Sprintnummer",
  "Sprintnaam": "Sprintnaam",
  "Startdatum": "Startdatum",
  "Einddatum": "Einddatum",
  "Sprintlengte (dagen)": "Sprintlengte (dagen)",
  "Show & Grow Datum": "Show & Grow Datum",
  "Show & Grow": "Show & Grow",
  "Show & Grow op woensdag": "Show & Grow op woensdag",
  "Vakantie verlenging": "Vakantie verlenging",
  "Verlengd met {days} vakantiedagen": "Verlengd met {days} vakantiedagen",
  "Vakanties": "Vakanties",
  "Vakantiebeheer": "Vakantiebeheer",
  "Nieuwe vakantie": "Nieuwe vakantie",
  "Vakantie toevoegen": "Vakantie toevoegen",
  "Vakantie bewerken": "Vakantie bewerken",
  "Vakantie verwijderen": "Vakantie verwijderen",
  "Vakantienaam": "Vakantienaam",
  "Geen vakanties geregistreerd.": "Geen vakanties geregistreerd.",
  "Planning": "Planning",
  "Feedback": "Feedback",
  "Zelfevaluatie": "Zelfevaluatie",
  "Zelfevaluatie & Beoordeling": "Zelfevaluatie & Beoordeling",
  "Docentbeoordeling": "Docentbeoordeling",
  "Reflectie": "Reflectie",
  "Voortgang": "Voortgang",
  "Voortgangsdashboard": "Voortgangsdashboard",
  "Kennisdeling": "Kennisdeling",
  "Hulp aan medestudenten": "Hulp aan medestudenten",
  "Peer Help": "Peer Help",
  "Nieuwe hulp registratie": "Nieuwe hulp registratie",
  "Kennisdeling registreren": "Kennisdeling registreren",
  "Naam medestudent": "Naam medestudent",
  "Toelichting geboden hulp": "Toelichting geboden hulp",
  "Links naar documentatie/code": "Links naar documentatie/code",
  "Geen kennisdeling geregistreerd.": "Geen kennisdeling geregistreerd.",
  "Stories": "Stories",
  "Nieuwe Story": "Nieuwe Story",
  "Story toevoegen": "Story toevoegen",
  "Story bewerken": "Story bewerken",
  "Story verwijderen": "Story verwijderen",
  "Story Type": "Story Type",
  "Story nummer": "Story nummer",
  "Titel": "Titel",
  "Als [rol]": "Als [rol]",
  "wil ik [wens]": "wil ik [wens]",
  "zodat [doel]": "zodat [doel]",
  "Acceptatiecriteria": "Acceptatiecriteria",
  "Kwaliteitscriteria": "Kwaliteitscriteria",
  "Criterium toevoegen": "Criterium toevoegen",
  "Criterium": "Criterium",
  "Subtaak": "Subtaak",
  "Subtaak toevoegen": "Subtaak toevoegen",
  "Inspringen als subtaak": "Inspringen als subtaak",
  "Terugspringen naar hoofdtaak": "Terugspringen naar hoofdtaak",
  "Bewijslast": "Bewijslast",
  "Bewijslast toevoegen": "Bewijslast toevoegen",
  "Bewijsstukken & resultaten": "Bewijsstukken & resultaten",
  "Bewijsstukken & resultaten (GitHub, Live URL, Document)": "Bewijsstukken & resultaten (GitHub, Live URL, Document)",
  "Document uploaden": "Document uploaden",
  "GitHub link": "GitHub link",
  "Live URL": "Live URL",
  "Document": "Document",
  "Link": "Link",
  "Leeruitkomsten": "Leeruitkomsten",
  "Leeruitkomst": "Leeruitkomst",
  "Leeruitkomst 1": "Leeruitkomst 1",
  "Leeruitkomst 2": "Leeruitkomst 2",
  "Leeruitkomst 3": "Leeruitkomst 3",
  "Leeruitkomst 4": "Leeruitkomst 4",
  "Leeruitkomst 5": "Leeruitkomst 5",
  "LU 1": "LU 1",
  "LU 2": "LU 2",
  "LU 3": "LU 3",
  "LU 4": "LU 4",
  "LU 5": "LU 5",
  "Waarschuwing": "Waarschuwing",
  "Minder dan 3 leeruitkomsten geselecteerd in deze sprint.": "Minder dan 3 leeruitkomsten geselecteerd in deze sprint.",
  "Leeruitkomst 5 (LU 5) ontbreekt in deze sprint.": "Leeruitkomst 5 (LU 5) ontbreekt in deze sprint.",
  "Officiële Voldoendes": "Officiële Voldoendes",
  "Prognose": "Prognose",
  "Docentoordeel": "Docentoordeel",
  "Voldoende": "Voldoende",
  "Onvoldoende": "Onvoldoende",
  "Niet beoordeeld": "Niet beoordeeld",
  "Automatisch invullen": "Automatisch invullen",
  "Argumentatie en bewijs": "Argumentatie en bewijs",
  "Niveau": "Niveau",
  "Van wie": "Van wie",
  "Jouw actie": "Jouw actie",
  "Feedbackregel toevoegen": "Feedbackregel toevoegen",
  "Geen feedbackregels ingevuld.": "Geen feedbackregels ingevuld.",
  "Wat heb je geleerd?": "Wat heb je geleerd?",
  "Wat behoud je?": "Wat behoud je?",
  "Wat ga je anders doen?": "Wat ga je anders doen?",
  "Exporteer Sprint": "Exporteer Sprint",
  "Exporteer Portfolio": "Exporteer Portfolio",
  "Download PDF": "Download PDF",
  "Download Excel": "Download Excel",
  "Verzamelexport (Alle Sprints)": "Verzamelexport (Alle Sprints)",
  "Feedback ontbreekt": "Feedback ontbreekt",
  "Er zijn nog geen feedbackregels ingevuld voor deze sprint. Weet je zeker dat je wilt exporteren?": "Er zijn nog geen feedbackregels ingevuld voor deze sprint. Weet je zeker dat je wilt exporteren?",
  "Negeren en downloaden": "Negeren en downloaden",
  "Ga naar feedback invoeren": "Ga naar feedback invoeren",
  "Aangepaste Story Typen": "Aangepaste Story Typen",
  "Story Type toevoegen": "Story Type toevoegen",
  "Type Code": "Type Code",
  "Type Naam": "Type Naam",
  "Kleur": "Kleur",
  "Actieve Sprint": "Actieve Sprint",
  "Eerstvolgende Show & Grow": "Eerstvolgende Show & Grow",
  "Dagen tot Show & Grow": "Dagen tot Show & Grow",
  "Geen actieve sprint": "Geen actieve sprint",
  "Geen stories in deze sprint": "Geen stories in deze sprint",
  "To Do": "To Do",
  "Bezig": "Bezig",
  "Voltooid": "Voltooid",
  "Alle sprints bekijken": "Alle sprints bekijken",
  "Terug naar sprintoverzicht": "Terug naar sprintoverzicht",
  "Terug naar dashboard": "Terug naar dashboard",

  // Presentation & Show and Tell
  "Presentatie": "Presentatie",
  "Presentatie starten": "Presentatie starten",
  "Show & Tell": "Show & Tell",
  "Show & Tell Presentatie": "Show & Tell Presentatie",
  "Volgende dia": "Volgende dia",
  "Vorige dia": "Vorige dia",
  "Volledig scherm": "Volledig scherm",
  "Volledig scherm verlaten": "Volledig scherm verlaten",
  "Volledig scherm (F)": "Volledig scherm (F)",
  "Volledig scherm verlaten (F)": "Volledig scherm verlaten (F)",
  "Volledig scherm geactiveerd": "Volledig scherm geactiveerd (Druk op F om te verlaten)",
  "Afbeelding vergroten": "Afbeelding vergroten",
  "Sluiten": "Sluiten",
  "Dia": "Dia",
  "van": "van",
  "Wat is er gerealiseerd": "Wat is er gerealiseerd",
  "Bekijk live applicatie": "Bekijk live applicatie",
  "Live Demo": "Live Demo",
  "Openen in nieuw tabblad": "Openen in nieuw tabblad",
  "Show & Tell content bewerken": "Show & Tell content bewerken",
  "Presentatie content": "Presentatie content",
  "Opnemen in presentatie": "Opnemen in presentatie",
  "Dia layout": "Dia layout",
  "Automatisch (aanbevolen)": "Automatisch (aanbevolen)",
  "Split (Tekst & Media)": "Split (Tekst & Media)",
  "Media Galerij": "Media Galerij",
  "Highlights & Doelen": "Highlights & Doelen",
  "Live Demo Focus": "Live Demo Focus",
  "Highlights / Bulletpoints": "Highlights / Bulletpoints",
  "Highlight toevoegen": "Highlight toevoegen",
  "Screenshot / Afbeelding toevoegen": "Screenshot / Afbeelding toevoegen",
  "Afbeelding URL of upload": "Afbeelding URL of upload",
  "Onderschrift (optioneel)": "Onderschrift (optioneel)",
  "Live Deployed URL": "Live Deployed URL",
  "URL titel": "URL titel",
  "Presentator notities": "Presentator notities",
  "Vragen & Feedback": "Vragen & Feedback",
  "Einde van de Show & Tell presentatie": "Einde van de Show & Tell presentatie",
  "Geen stories beschikbaar voor de presentatie": "Geen stories beschikbaar voor de presentatie",
  "Miniaturen & Overzicht": "Miniaturen & Overzicht",
  "Introductie": "Introductie",
  "Afsluiting": "Afsluiting",
  "Gedeployde URL": "Gedeployde URL",
  "Bewijsstukken": "Bewijsstukken",
  "Server Shutdown": "Server Nachtafsluiting",
  "Automatic Shutdown": "Automatische Nachtafsluiting",
  "Scheduled Shutdown": "Geplande Afsluiting",
  "Shutdown Time": "Afsluitingstijd",
  "Next shutdown": "Volgende afsluiting",
  "Shutdown blocked": "Afsluiting geblokkeerd",
  "Block Tonight": "Blokkeer nachtafsluiting",
  "Unblock Shutdown": "Deblokkeer afsluiting",
  "Save Time": "Tijd opslaan",
  "Shutdown schedule updated": "Afsluitingsschema bijgewerkt",
  "Shutdown blocked for tonight": "Nachtafsluiting geblokkeerd voor vannacht",
  "Shutdown unblocked": "Nachtafsluiting gedeblokkeerd",
  "Minecraft player warnings and safe shutdown active": "Minecraft spelers ontvangen 10m, 5m en 1m van tevoren een waarschuwing in de chat. Bij afsluiting worden alle werelden veilig opgeslagen voordat de Fedora server uitschakelt.",
  "Automatic server shutdown active": "Automatische serverafsluiting actief",
  "Server shutdown is blocked for tonight": "Serverafsluiting is voor vannacht geblokkeerd",
  "Automatic server shutdown is disabled": "Automatische serverafsluiting is uitgeschakeld",
  "Contract / Overeenkomst (PDF)": "Contract / Overeenkomst (PDF)",
  "Contract / Overeenkomst": "Contract / Overeenkomst",
  "Contract toevoegen": "Contract toevoegen",
  "Contract wijzigen": "Contract wijzigen",
  "Contract uploaden": "Contract uploaden",
  "Overeenkomst bekijken": "Overeenkomst bekijken",
  "Contract bekijken": "Contract bekijken",
  "Geen contract toegevoegd": "Geen contract toegevoegd",
  "Contract verwijderen": "Contract verwijderen",
  "Upload een PDF-contract of overeenkomst": "Upload een PDF-contract of overeenkomst (max 20MB)",
  "Contract": "Contract",
  "Overeenkomst": "Overeenkomst",
  "Contract details": "Contract details",
  "Downloaden": "Downloaden",
  "Download contract": "Download contract",
  "PDF uploaden mislukt": "PDF uploaden mislukt",
  "Alleen PDF-bestanden zijn toegestaan.": "Alleen PDF-bestanden zijn toegestaan.",
  "Uitgaven": "Uitgaven",
  "Nieuwe uitgave": "Nieuwe uitgave",
  "Uitgave toevoegen": "Uitgave toevoegen",
  "Uitgave bewerken": "Uitgave bewerken",
  "Selecteer categorie": "Selecteer categorie",
  "Geen handelsnaam": "Geen handelsnaam (Algemeen)",
  "Bon / Factuur (PDF of afbeelding)": "Bon / Factuur (PDF of afbeelding)",
  "Bon / Factuur": "Bon / Factuur",
  "Bon bekijken": "Bon bekijken",
  "Bon toevoegen": "Bon toevoegen",
  "Bon wijzigen": "Bon wijzigen",
  "Bon verwijderen": "Bon verwijderen",
  "Upload een bon of factuur": "Upload een bon of factuur (PDF / JPG / PNG, max 20MB)",
  "Notities (optioneel)": "Notities (optioneel)",
  "Omschrijving van de uitgave is verplicht.": "Omschrijving van de uitgave is verplicht.",
  "Bedrag is verplicht en moet groter zijn dan 0.": "Bedrag is verplicht en moet groter zijn dan 0.",
  "Deze uitgave verwijderen?": "Deze uitgave verwijderen?",
  "Geen uitgaven gevonden.": "Geen uitgaven gevonden.",
  "Voeg je eerste uitgave toe": "Voeg je eerste uitgave toe",
  "Software & Abonnementen": "Software & Abonnementen",
  "Hardware & Apparatuur": "Hardware & Apparatuur",
  "Kantoor & Werkplek": "Kantoor & Werkplek",
  "Marketing & Verkoop": "Marketing & Verkoop",
  "Administratie & Verzekeringen": "Administratie & Verzekeringen",
  "Netto resultaat": "Netto resultaat",
  "Totale uitgaven": "Totale uitgaven",
  "Uitgaven per maand": "Uitgaven per maand",
  "Uitgaven per categorie": "Uitgaven per categorie",
  "Uitgaven bekijken": "Uitgaven bekijken",
  "Alle categorieën": "Alle categorieën",
  "Alle handelsnamen": "Alle handelsnamen",
  "Bijlage gekoppeld": "Bijlage gekoppeld",
  "Bestand uploaden mislukt": "Bestand uploaden mislukt",
};



export function t(key: string, params?: Record<string, string>): string {
  let text = nl[key] ?? key;
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      text = text.replace(`{${k}}`, v);
    }
  }
  return text;
}
